name: Deploy Flask App
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Use the Makefile to build and push the Docker image
      - name: Build and Push Docker Image
        run: |
          make push

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use the Makefile to create a Kind cluster, load the image, and deploy
      - name: Deploy to Kubernetes
        run: |
          make kind-cluster
          make load-image
          make deploy
