# name: Deploy Flask App
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - name: Build Docker image
#         run: |
#           docker build -t joannetich/simple-webapp-flask:latest
#           docker push joannetich/simple-webapp-flask:latest
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: Set up Kind
#         uses: helm/kind-action@v1
#         with:
#           version: v0.21.0
#       - name: Create Kind cluster
#         run: kind create cluster --name webapp
#       - name: Load Docker image into Kind
#         run: |
#           kind load docker-image joannetich/simple-webapp-flask:latest
#       - name: Apply Kubernetes manifests
#         run: |
#           kubectl apply -f k8s-deployment.ya


          
name: Deploy Flask App
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -t joannetich/simple-webapp-flask:latest .
          docker push joannetich/simple-webapp-flask:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Kind
        uses: helm/kind-action@v1
        with:
          version: v0.21.0
      - name: Create Kind cluster
        run: kind create cluster --name webapp
      - name: Load Docker image into Kind
        run: |
          sudo docker pull joannetich/simple-webapp-flask:latest
          sudo kind load docker-image joannetich/simple-webapp-flask:latest --name webapp
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s-deployment.yaml






